ColegioPublic/Controllers/AlumnoController.cs
using ColegioPublic.Extensions;
using ColegioPublic.Helper;
using ColegioPublic.ViewsModel.AlumnoVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class AlumnoController : BaseController
    {

        // GET: Alumno
        public ActionResult Index(IndexAlumnoViewModel model)
        {
      
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }

        public async Task<PartialViewResult> _ListAlumno(int? p, IndexAlumnoViewModel model)
        {
            _ListAlumnoViewModel listModel = new _ListAlumnoViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }

        public ActionResult AddEditAlumno(int? idAlumno)
        {
            AddEditAlumnoViewModel model = new AddEditAlumnoViewModel();
            model.Fill(_CargarDatosContext,idAlumno);
            return View(model);
        }

        [HttpPost]
        public ActionResult AddEditAlumno(AddEditAlumnoViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TryUpdateModel(model);
                    return View(model);
                }
                //if (model.Image != null)
                //{
                //    string archivo = (DateTime.Now.ToString("yyyyMMddHHmmss") + "-" + model.Image.FileName).ToLower();
                //    model.Image.SaveAs(Server.MapPath("~/File/Alumno/" + archivo));
                //    model.RutaFoto = Server.MapPath("~/File/Alumno/" + archivo);
                //}

                AddEditAlumnoViewModel addEdit = new AddEditAlumnoViewModel();
                addEdit.AddEdit(_CargarDatosContext, model);
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.AddNotification($"Error al guardar datos ", NotificationType.ERROR);
                return View(model);
            }
        }
        public ActionResult Delete(int AlumnoId)
        {

            try
            {
                AddEditAlumnoViewModel model = new AddEditAlumnoViewModel();
                model.Delete(_CargarDatosContext, AlumnoId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

ColegioPublic/Controllers/CursoController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.CursoVM;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class CursoController : BaseController
    {
        string Baseurl = "http://localhost:1478";
        // GET: Curso
        public ActionResult Index(IndexCursoViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }
        public async Task<PartialViewResult> _ListCurso(int? p, IndexCursoViewModel model)
        {
            _ListCursoViewModel listModel = new _ListCursoViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }
        public ActionResult AddEditCurso(int ? idCurso)
        {
            AddEditCursoViewModel model = new AddEditCursoViewModel();
            model.Fill(_CargarDatosContext, idCurso);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> AddEditCurso(AddEditCursoViewModel model)
        {
            List<AddEditCursoViewModel> EmpInfo = new List<AddEditCursoViewModel>();
            using (var client = new HttpClient())
            {
                model.cursoId = model.cursoId??0;
                model.estadoId = 1;

                var json = JsonConvert.SerializeObject(model);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                var url = ConfigurationManager.AppSettings["WebApiBase"] + "/api/Curso/Cursos/Create";
                var response = await client.PostAsync(url, data);
                string result = response.Content.ReadAsStringAsync().Result;
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
        }
        public ActionResult Delete(int CursoId)
        {

            try
            {
                AddEditCursoViewModel model = new AddEditCursoViewModel();
                model.Delete(_CargarDatosContext, CursoId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

ColegioPublic/Views/Usuario/AddEditUsuario.cshtml
@model ColegioPublic.ViewsModel.UserVM
@{
    ViewBag.Title = "Agregar Usuario ";
}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">@(Model.cursoId.HasValue ? "Agregar " : "Editar ")Usuario </h4>
                <form class="form" action="@Url.Action("AddEditCurso","Curso")" method="post">
                    @Html.HiddenFor(x => x.ac)
                    <div class="form-group mt-5 row">
                        @Html.LabelFor(x => x.nombre, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextBoxFor(x => x.nombre, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group mt-5 row">
                        @Html.LabelFor(x => x.image, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextBoxFor(x => x.image, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="card-body">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                            <button type="button" class="btn btn-dark">Cancel</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

        $(function () {

        });
    </script>
}

ColegioPublic/Views/Usuario/Index.cshtml
@model ColegioPublic.ViewsModel.AlumnoVM.IndexAlumnoViewModel
@{
    ViewBag.Title = "Lista Alumno";
}

<h2>Lista de Alumnos</h2>

@using (Ajax.BeginForm("_ListAlumno", "Alumno", new AjaxOptions
{//GetPatients is name of method in PatientController
    InsertionMode = InsertionMode.Replace, //target element(#patientList) will be replaced
    UpdateTargetId = "paged-section",
    LoadingElementId = "loader" // div with .gif loader - that is shown when data are loading
}))
{
    @Html.LabelFor(x => x.q, new { })
    <div class="input-group">

        @Html.TextBoxFor(x => x.q, new { @class = "form-control" })
        <button class="btn btn-success btn-sm"><i class="fa fa-search" aria-hidden="true"></i></button>
    </div>

}
<hr />
<div class="button-group text-right">
    <a href="@Url.Action("AddEditAlumno","Alumno")" class="btn btn-success"> <i class="fa fa-plus-circle" aria-hidden="true"></i> Nuevo Alumno</a>
</div>

<div class="table-responsive" id="paged-section">
    @{Html.RenderAction("_ListAlumno", Model);}
</div>

ColegioPublic/Views/Usuario/_ListUsuario.cshtml
@model ColegioPublic.ViewsModel.AlumnoVM._ListAlumnoViewModel
@using PagedList.Mvc;
@using PagedList;
@using ColegioPublic.Helper;

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            <th>Apellido Paterno</th>
            <th>Apellido Materno</th>
            <th>Dni</th>
            <th>Fecha Nacimiento</th>
            <th>Acciones</th>

        </tr>
    </thead>

    <tbody>
        @if (Model.LstRegistro.Count > 0)
        {
            foreach (var item in Model.LstRegistro)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td>@item.ApellidoPaterno</td>
                    <td>@item.ApellidoMaterno</td>
                    <td>@item.Dni</td>
                    <td>@item.FechaNacimiento</td>

                    <td>
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Opciones</button>
                            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(696px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="@Url.Action("AddEditAlumno","Alumno", new {idAlumno = item.AlumnoId})">Editar</a>
                                <a class="dropdown-item" href="@Url.Action("AddEditAlumno","Alumno", new {idAlumno = item.AlumnoId})">Eliminar</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        }

    </tbody>
</table>
@Html.PagedListPager(Model.LstRegistro, p => Url.Action("_ListAlumno", new { p = p }), PaginationHelper.AjaxPagerOptionsDefault)