ColegioPublic/Controllers/AlumnoController.cs
using ColegioPublic.Extensions;
using ColegioPublic.Helper;
using ColegioPublic.ViewsModel.AlumnoVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class AlumnoController : BaseController
    {

        // GET: Alumno
        public ActionResult Index(IndexAlumnoViewModel model)
        {
      
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }

        public async Task<PartialViewResult> _ListAlumno(int? p, IndexAlumnoViewModel model)
        {
            _ListAlumnoViewModel listModel = new _ListAlumnoViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }

        public ActionResult AddEditAlumno(int? idAlumno)
        {
            AddEditAlumnoViewModel model = new AddEditAlumnoViewModel();
            model.Fill(_CargarDatosContext,idAlumno);
            return View(model);
        }

        [HttpPost]
        public ActionResult AddEditAlumno(AddEditAlumnoViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TryUpdateModel(model);
                    return View(model);
                }
                //if (model.Image != null)
                //{
                //    string archivo = (DateTime.Now.ToString("yyyyMMddHHmmss") + "-" + model.Image.FileName).ToLower();
                //    model.Image.SaveAs(Server.MapPath("~/File/Alumno/" + archivo));
                //    model.RutaFoto = Server.MapPath("~/File/Alumno/" + archivo);
                //}

                AddEditAlumnoViewModel addEdit = new AddEditAlumnoViewModel();
                addEdit.AddEdit(_CargarDatosContext, model);
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                this.AddNotification($"Error al guardar datos ", NotificationType.ERROR);
                return View(model);
            }
        }
        public ActionResult Delete(int AlumnoId)
        {

            try
            {
                AddEditAlumnoViewModel model = new AddEditAlumnoViewModel();
                model.Delete(_CargarDatosContext, AlumnoId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

ColegioPublic/Controllers/MatriculaController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.MatriculaVM;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class MatriculaController : BaseController
    {
        string Baseurl = "http://localhost:1478";
        // GET: Matricula
        public ActionResult Index(IndexMatriculaViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }
        public async Task<PartialViewResult> _ListMatricula(int? p, IndexMatriculaViewModel model)
        {
            _ListMatriculaViewModel listModel = new _ListMatriculaViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }
        public ActionResult AddEditMatricula(int? idAlumno,int? idMatricula)
        {
            AddEditMatriculaViewModel model = new AddEditMatriculaViewModel();
            model.FillByAlumno(_CargarDatosContext, idAlumno);
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> AddEditMatricula(AddEditMatriculaViewModel model)
        {

            List<AddEditMatriculaViewModel> EmpInfo = new List<AddEditMatriculaViewModel>();
            using (var client = new HttpClient())
            {
                model.matriculaId = 0;
                model.estadoId = 1;
                model.fechaCreacion = DateTime.Now;

                var json = JsonConvert.SerializeObject(model);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                var url = ConfigurationManager.AppSettings["WebApiBase"] + "/api/Matricula/Matricula/Create";
                var response = await client.PostAsync(url, data);
                string result = response.Content.ReadAsStringAsync().Result;

                return  RedirectToAction("Index",new {q = model.alumnoId });
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
            }
        }

        public ActionResult Delete(int MatriculaId)
        {

            try
            {
                AddEditMatriculaViewModel model = new AddEditMatriculaViewModel();
                model.Delete(_CargarDatosContext, MatriculaId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

ColegioPublic/Views/Alumno/AddEditAlumno.cshtml
@model ColegioPublic.ViewsModel.AlumnoVM.AddEditAlumnoViewModel
@{
    ViewBag.Title =Model.AlumnoId.HasValue?"Agregar " :"Editar " + " Alumno";
}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">@(Model.AlumnoId.HasValue?"Agregar " :"Editar ")Alumno</h4>
                <form class="form" action="@Url.Action("AddEditAlumno","Alumno")" method="post" enctype="multipart/form-data">
                    @Html.HiddenFor(x => x.AlumnoId)
                    <div class="form-group mt-5 row">
                        @Html.LabelFor(x => x.Nombre, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
                        </div>
                        @Html.ValidationMessageFor(x => x.Nombre)
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(x => x.ApellidoPaterno, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextBoxFor(x => x.ApellidoPaterno, new { @class = "form-control" })
                        </div>
                        @Html.ValidationMessageFor(x => x.ApellidoPaterno)
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(x => x.ApellidoMaterno, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextBoxFor(x => x.ApellidoMaterno, new { @class = "form-control" })
                        </div>
                        @Html.ValidationMessageFor(x => x.ApellidoMaterno)
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(x => x.Dni, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextBoxFor(x => x.Dni, new { @class = "form-control" })
                        </div>
                        @Html.ValidationMessageFor(x => x.Dni)
                    </div>
                    <div class="form-group row">

                        @Html.LabelFor(x => x.FechaNacimiento, new { @class = "col-2 col-form-label" })

                        <div class="col-10">

                            @Html.TextBoxFor(x => x.FechaNacimiento, "{0:dd/MM/yyyy}", new { @class = "form-control datetimepicker1" })
                        </div>
                        @Html.ValidationMessageFor(x => x.FechaNacimiento)
                    </div>
                    <div class="form-group">
                        <label>Custom File upload</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Imagen Alumno</span>
                            </div>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="Image" name="Image">
                                <label class="custom-file-label" id="nameFile" for="Image">Choose file</label>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(x => x.Image)
                    </div>

                    <div class="form-actions">
                        <div class="card-body">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>
                            <a href="@Url.Action("Index","Alumno")">Cancelar</a>
                         
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

        $(function () {

        
            document.getElementById('Image').onchange = function () {
              console.log(this.value);
              document.getElementById('nameFile').innerHTML = document.getElementById('Image').files[0].name;
            }


        });
    </script>
}

ColegioPublic/Views/Alumno/Index.cshtml
@model ColegioPublic.ViewsModel.AlumnoVM.IndexAlumnoViewModel
@{
    ViewBag.Title = "Lista Alumno";
}

<h2>Lista de Alumnos</h2>

@using (Ajax.BeginForm("_ListAlumno", "Alumno", new AjaxOptions
{//GetPatients is name of method in PatientController
    InsertionMode = InsertionMode.Replace, //target element(#patientList) will be replaced
    UpdateTargetId = "paged-section",
    LoadingElementId = "loader" // div with .gif loader - that is shown when data are loading
}))
{
    @Html.LabelFor(x => x.q, new { })
    <div class="input-group">

        @Html.TextBoxFor(x => x.q, new { @class = "form-control" })
        <button class="btn btn-success btn-sm" id="Filtrar"><i class="fa fa-search" aria-hidden="true"></i></button>
    </div>

}
<hr />
<div class="button-group text-right">
    <a href="@Url.Action("AddEditAlumno","Alumno")" class="btn btn-success"> <i class="fa fa-plus-circle" aria-hidden="true"></i> Nuevo Alumno</a>
</div>

<div class="table-responsive" id="paged-section">
    @{Html.RenderAction("_ListAlumno", Model);}
</div>

@section scripts{
    <script>

        $(function () {
          $("#paged-section").on("click",".eliminarAlumno",function (e) {
              e.preventDefault();
              var url = $(this).attr("href");
              debugger;
              var formData = new FormData();
              Swal.fire({
                  title: 'Confirmación de Eliminación',
                  text: "Está seguro de Eliminar?",
                  icon: 'warning',
                  showCancelButton: true,
                  confirmButtonColor: '#3085d6',
                  cancelButtonColor: '#d33',
                  cancelButtonText:'Cancelar',
                  confirmButtonText: 'Si, Estoy seguro!'
              }).then((result) => {
                  if (result.value) {
                      /**/
                      $.ajax({
                          url: url,
                          type: "GET",
                          data: formData,
                          contentType: false,
                          processData: false,
                          async: false
                      }).done(function (data) {
                          var modelo = JSON.parse(JSON.stringify(data));
                          if (modelo.Value == true) {
                              Swal.fire(
                                  'Se Elimino Correctamente!',
                                  '',
                                  'success'
                              ).then((result) => {
                                  if (result) {
                                      $("#Filtrar").submit();
                                  }
                              });
                          } else {
                              Swal.fire(
                                  'Ocurrio algún error al Eliminar!',
                                  '',
                                  'error'
                              )
                          }
                      }).fail(function () {
                          Swal.fire(
                              'No se pudo Eliminar!',
                              'Aceptar!',
                              'error'
                          )

                      });
                      /**/
                  }
              })

          });
        });


    </script>
}

ColegioPublic/Views/Alumno/_ListAlumno.cshtml
@model ColegioPublic.ViewsModel.AlumnoVM._ListAlumnoViewModel
@using PagedList.Mvc;
@using PagedList;
@using ColegioPublic.Helper;

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            <th>Apellido Paterno</th>
            <th>Apellido Materno</th>
            <th>Dni</th>
            <th>Fecha Nacimiento</th>
            <th>Acciones</th>
        
        </tr>
    </thead>

    <tbody>
        @if (Model.LstRegistro.Count > 0)
        {
            foreach (var item in Model.LstRegistro)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td>@item.ApellidoPaterno</td>
                    <td>@item.ApellidoMaterno</td>
                    <td>@item.Dni</td>
                    <td>@item.FechaNacimiento</td>
           
                    <td><div class="input-group-append">
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Opciones</button>
                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(696px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                        <a class="dropdown-item" href="@Url.Action("AddEditAlumno","Alumno", new {idAlumno = item.AlumnoId})">Editar</a>
                        <a class="dropdown-item" href="@Url.Action("AddEditMatricula","Matricula", new {idAlumno = item.AlumnoId})">Matricular</a>
                        <a class="dropdown-item" href="@Url.Action("Index","Matricula", new {q = item.AlumnoId})">Lista de Matriculas</a>
                        <a class="dropdown-item eliminarAlumno" href="@Url.Action("Delete","Alumno", new {AlumnoId = item.AlumnoId})">Eliminar</a>
                    </div>
                    </div>
                    </td>
                </tr>
            }
        }

    </tbody>
</table>

@Html.PagedListPager(Model.LstRegistro, p => Url.Action("_ListAlumno", new { p = p ,model = Model.q}), PaginationHelper.AjaxPagerOptionsDefault)