ColegioPublic/Controllers/AulaController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.AulaVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class AulaController : BaseController
    {
        // GET: Aula
        public ActionResult Index(IndexAulaViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }

        public async Task<PartialViewResult> _ListAula(int? p, IndexAulaViewModel model)
        {
            _ListAulaViewModel listModel = new _ListAulaViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }

        public ActionResult AddEditAula(int? AulaId)
        {
            AddEditAulaViewModel model = new AddEditAulaViewModel();
            model.Fill(_CargarDatosContext, AulaId);
            return View(model);
        }

        [HttpPost]
        public ActionResult AddEditAula(AddEditAulaViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TryUpdateModel(model);
                    return View(model);
                }

                AddEditAulaViewModel addEdit = new AddEditAulaViewModel();
                addEdit.AddEdit(_CargarDatosContext, model);
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                this.AddNotification($"Error al guardar datos ", NotificationType.ERROR);
                return View(model);
            }
        }

        public ActionResult Delete(int AulaId)
        {

            try
            {
                AddEditAulaViewModel model = new AddEditAulaViewModel();
                model.Delete(_CargarDatosContext, AulaId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

ColegioPublic/Controllers/CursoController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.CursoVM;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class CursoController : BaseController
    {
        string Baseurl = "http://localhost:1478";
        // GET: Curso
        public ActionResult Index(IndexCursoViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }
        public async Task<PartialViewResult> _ListCurso(int? p, IndexCursoViewModel model)
        {
            _ListCursoViewModel listModel = new _ListCursoViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }
        public ActionResult AddEditCurso(int ? idCurso)
        {
            AddEditCursoViewModel model = new AddEditCursoViewModel();
            model.Fill(_CargarDatosContext, idCurso);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> AddEditCurso(AddEditCursoViewModel model)
        {
            List<AddEditCursoViewModel> EmpInfo = new List<AddEditCursoViewModel>();
            using (var client = new HttpClient())
            {
                model.cursoId = model.cursoId??0;
                model.estadoId = 1;

                var json = JsonConvert.SerializeObject(model);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                var url = ConfigurationManager.AppSettings["WebApiBase"] + "/api/Curso/Cursos/Create";
                var response = await client.PostAsync(url, data);
                string result = response.Content.ReadAsStringAsync().Result;
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
        }
        public ActionResult Delete(int CursoId)
        {

            try
            {
                AddEditCursoViewModel model = new AddEditCursoViewModel();
                model.Delete(_CargarDatosContext, CursoId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

ColegioPublic/Controllers/NotaController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.NotaVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class NotaController : BaseController
    {
        // GET: Nota
        public ActionResult Index(IndexNotaViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }

        public async Task<PartialViewResult> _ListCurso(int? p, IndexNotaViewModel model)
        {
            _ListCursoViewModel listModel = new _ListCursoViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }

        public ActionResult AddEditNota (int CursoId,int GradoId)
        {
            AddEditNotaViewModel newNotas = new AddEditNotaViewModel();
            newNotas.Fill(_CargarDatosContext,CursoId,GradoId);
            return View(newNotas);
        }
        [HttpPost]
        public ActionResult AddEditNota(AddEditNotaViewModel model ,FormCollection formCollection)
        {
            try
            {
                AddEditNotaViewModel newNotas = new AddEditNotaViewModel();
                newNotas.AddEdit(_CargarDatosContext, model, formCollection);
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                this.AddNotification($"Error al guardar Notas", NotificationType.ERROR);
                throw;
            }
   
         
   
        }

    }
}

ColegioPublic/Controllers/UserController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.AlumnoVM;
using ColegioPublic.ViewsModel.UserVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class UserController : BaseController
    {
        public ActionResult Index(IndexUserViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }

        public async Task<PartialViewResult> _ListUser(int? p, IndexUserViewModel model)
        {
            _ListUserViewModel listModel = new _ListUserViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }

        public ActionResult AddEditUser(int? UserId)
        {
            AddEditUserViewModel model = new AddEditUserViewModel();
            model.Fill(_CargarDatosContext, UserId);
            return View(model);
        }

        [HttpPost]
        public ActionResult AddEditUser(AddEditUserViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TryUpdateModel(model);
                    return View(model);
                }

                AddEditUserViewModel addEdit = new AddEditUserViewModel();
                addEdit.AddEdit(_CargarDatosContext, model);
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                this.AddNotification("Error al guardar ", NotificationType.ERROR);
                return View(model);
            }
        }
        public ActionResult Delete(int UserId)
        {

            try
            {
                AddEditUserViewModel model = new AddEditUserViewModel();
                model.Delete(_CargarDatosContext, UserId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }


        }

    }
}

ColegioPublic/Views/Shared/Shared2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ColegioPublic/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Copyright &copy; 2020 NombreColegio.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Versión</b> 1.0.0
    </div>
</footer>

ColegioPublic/Views/Shared/_Header.cshtml
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <!-- Logo icon -->
                <b>
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="~/Content/assets/images/fse.png" width="50px" height="50px" alt="homepage" class="dark-logo" />
                    <!-- Light Logo icon -->
                    <img src="~/Content/assets/images/santiago.png" alt="homepage" class="light-logo" />
                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span>
                
                </span>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav  mt-md-0 ">
                <!-- This is  -->
                <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                <li class="nav-item"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="icon-arrow-left-circle"></i></a> </li>
                <!-- ============================================================== -->
                <!-- Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->
            </ul>
         

            <!-- ============================================================== -->
            <!-- User profile and search -->
            <!-- ============================================================== -->
            <div class="navbar-nav my-lg-0 mx-auto">
                
                    <h2 class="text-white"><b>IE. Felipe Santiago Estenos</b></h2>
               
            </div>
        </div>
    </nav>
</header>

ColegioPublic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/assets/images/favicon.png">
    <title>Colegio Público</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link href="~/Content/assets/plugins/toast-master/css/jquery.toast.css" rel="stylesheet">
    <link href="~/Content/main/css/style.css" rel="stylesheet">
    <link href="~/Content/main/css/colors/blue.css" id="theme" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/PagedList.css" />
</head>

<body class="fix-header fix-sidebar card-no-border">

    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>

    <div id="main-wrapper">

        @{Html.RenderPartial("_Header");}
        @{Html.RenderPartial("_SideBar");}
        <div class="page-wrapper" style="min-height: 686px;">
            <div class="container-fluid">

                @Html.Raw(Html.BuildBreadcrumbNavigation())
                @Html.Partial("_Notifications")
                @RenderBody()
            </div>
        </div>

        <footer class="footer">
            © 2020 IE. Felipe Santiago Estenos
        </footer>

    </div>

    <script src="~/Content/assets/plugins/jquery/jquery.min.js"></script>
    <script src="~/Content/assets/plugins/bootstrap/js/popper.min.js"></script>
    <script src="~/Content/assets//plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Content/main/js/jquery.slimscroll.js"></script>
    <script src="~/Content/main/js/waves.js"></script>
    <script src="~/Content/main/js/sidebarmenu.js"></script>
    <script src="~/Content/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <script src="~/Content/main/js/custom.min.js"></script>

    <script src="~/Content/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
    <script src="~/Content/main/js/dashboard1.js"></script>
    <script src="~/Content/main/js/toastr.js"></script>

    @*@Scripts.Render("~/bundles/jquery")*@

    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    @*<script type="text/javascript" src="~/Scripts/jquery-3.4.1.js"></script>*@
    <script type="text/javascript" src="~/Scripts/moment.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <!-- <link rel="stylesheet" type="text/css" href="css/bootstrap-datetimepicker.css"> -->
    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker.min.css">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/css/bootstrap-datetimepicker-standalone.css">
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.43/js/bootstrap-datetimepicker.min.js"></script>
    -->
    <link rel="stylesheet" href="~/Content/bootstrap-datetimepicker.css" />
    <script>
        $(function () {


            $(".datetimepicker1").datetimepicker({
                format: 'MM-DD-YYYY',
                //format: 'DD-MM-YYYY',

            });


        });


    </script>

</body>
</html>

ColegioPublic/Views/Shared/_NavBar.cshtml
  <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->

</nav>
<!-- /.navbar -->

ColegioPublic/Views/Shared/_Notifications.cshtml
@using ColegioPublic.Extensions

@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
<!-- display errors -->
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(errorList.Count() > 1){
            <strong><span class="glyphicon glyphicon-remove"></span> There are @errorList.Count() errors: </strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-remove"></span> Error: </strong>
            @Html.Raw(errorList.First())
        }
    </div>
}

<!-- display warnings -->
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(warningList.Count() > 1){
            <strong><span class="glyphicon glyphicon-warning-sign"></span> There are @warningList.Count() warnings: </strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-warning-sign"></span> Warning: </strong>
            @Html.Raw(warningList.First())
        }
    </div>
}

<!-- display success -->
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(successList.Count() > 1){
            <strong><span class="glyphicon glyphicon-ok"></span> There are @successList.Count() successful notifications: </strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-ok"></span> Success! </strong>
            @Html.Raw(successList.First())
        }
    </div>
}

<!-- display success -->
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(infoList.Count() > 1){
            <strong><span class="glyphicon glyphicon-info-sign"></span> There are @infoList.Count() notifications: </strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-info-sign"></span> </strong>
            @Html.Raw(infoList.First())
        }
    </div>
}

ColegioPublic/Views/Shared/_SideBar.cshtml
@using ColegioPublic.Helper
@{
   
    var rol = Session.GetRol();
}


<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User profile -->
        <div class="user-profile">
            <!-- User profile image -->
            <div class="profile-img"> <img src="~/Content/assets/images/users/1.jpg" alt="user" /> </div>
            <!-- User profile text-->
            <div class="profile-text">

            </div>
        </div>
        <!-- End User profile text-->
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-small-cap">PERSONAL</li>
                @if (rol.Equals("admin"))
                {
                    <li>
                        <a class="has-arrow" href="#" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Matenimiento <span class="label label-rounded label-success">5</span></span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="@Url.Action("Index","Alumno")">Alumno</a></li>
                            <li><a href="@Url.Action("Index","Curso")">Curso</a></li>
                            <li><a href="@Url.Action("Index","Profesor")">Profesor</a></li>
                            <li><a href="@Url.Action("Index","Aula")">Aulas</a></li>
                            <li><a href="@Url.Action("Index","Actividad")">Actividades</a></li>
                            <li><a href="@Url.Action("Index","UsuarioMovil")">Usuarios APP</a></li>
                            <li><a href="@Url.Action("Index","User")">Usuarios Web</a></li>
                        </ul>
                    </li>
                }

                <li>
                    <a class="has-arrow " href="#" aria-expanded="false"><i class="mdi mdi-bullseye"></i><span class="hide-menu">Operaciones</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="@Url.Action("Index","Horario")">Horarios</a></li>
                        <li><a href="@Url.Action("Index","Notificacion")">Notificación</a></li>
                        <li><a href="@Url.Action("IndexCurso","Examen")">Examenes</a></li>
                        <li><a href="@Url.Action("Index","Nota")">Notas</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <!-- Bottom points-->
    <div class="sidebar-footer text-center">

        <a href="@Url.Action("CerrarSesion","login")" class="link text-center" data-toggle="tooltip" title="Cerrar Sesión"><i class="mdi mdi-power"></i></a>

    </div>
    <!-- End Bottom points-->
</aside>