ColegioPublic/Controllers/NotificacionController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.NotificacionVM;
using ColegioPublic.ViewsModel.UsuarioMovilVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class NotificacionController : BaseController
    {
        public ActionResult Index(IndexUsuarioMovilViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }

        public async Task<PartialViewResult> _ListUsuarioMovil(int? p, IndexUsuarioMovilViewModel model)
        {
            _ListUsuarioMovilViewModel listModel = new _ListUsuarioMovilViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }
        public ActionResult _ListNotificacion(int usuarioId)
        {
            try
            {
                _ListNotificacionViewModel model = new _ListNotificacionViewModel();
                model.Fill(_CargarDatosContext, usuarioId);
                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }
        public ActionResult AddNotification(int usuarioId,int?NotificacionId)
        {
            try
            {
                AddEditNotificacionViewModel model = new AddEditNotificacionViewModel();
                model.Fill(_CargarDatosContext,usuarioId,NotificacionId);
                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
    
        }
        [HttpPost]
        public ActionResult AddNotification(AddEditNotificacionViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TryUpdateModel(model);
                    return View(model);
                }
                AddEditNotificacionViewModel addNotificacion = new AddEditNotificacionViewModel();
                addNotificacion.AddEditNotificacion(_CargarDatosContext, model);
            
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return View("Index");
            }
            catch (Exception)
            {
                this.AddNotification($"Error al guardar datos", NotificationType.ERROR);
                return View(model);
            }
        }

        public ActionResult Delete(int NotificacionId)
        {

            try
            {
                AddEditNotificacionViewModel model = new AddEditNotificacionViewModel();
                model.Delete(_CargarDatosContext, NotificacionId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }

        }

    }
}

ColegioPublic/Controllers/UsuarioMovilController.cs
using ColegioPublic.Extensions;
using ColegioPublic.ViewsModel.AlumnoVM;
using ColegioPublic.ViewsModel.UsuarioMovilVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ColegioPublic.Controllers
{
    public class UsuarioMovilController : BaseController
    {
        // GET: UsuarioMovil
        public ActionResult Index(IndexUsuarioMovilViewModel model)
        {
            model.Fill(_CargarDatosContext, model);
            return View(model);
        }

        public async Task<PartialViewResult> _ListUsuarioMovil(int? p, IndexUsuarioMovilViewModel model)
        {
            _ListUsuarioMovilViewModel listModel = new _ListUsuarioMovilViewModel();
            await listModel.FillList(_CargarDatosContext, model, p);
            return PartialView(listModel);
        }

        public ActionResult AddEditUsuarioMovil(int? UserId)
        {
            AddEditUsuarioMovilViewModel model = new AddEditUsuarioMovilViewModel();
            model.Fill(_CargarDatosContext, UserId);
            return View(model);
        }

        [HttpPost]
        public ActionResult AddEditUsuarioMovil(AddEditUsuarioMovilViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TryUpdateModel(model);
                    return View(model);
                }

                AddEditUsuarioMovilViewModel addEdit = new AddEditUsuarioMovilViewModel();
                addEdit.AddEdit(_CargarDatosContext, model);
                this.AddNotification($"Se Guardaron correctamente los datos", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                this.AddNotification($"Error al guardar ", NotificationType.ERROR);
                throw;
            }
        }
        public ActionResult Delete(int  UsuarioId)
        { 
            try
            {
                AddEditUsuarioMovilViewModel model = new AddEditUsuarioMovilViewModel();
                model.Delete(_CargarDatosContext, UsuarioId);
                return Json(new { Value = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { Value = false }, JsonRequestBehavior.AllowGet);
            }
           
      
        }
    }
}

ColegioPublic/Views/Notificacion/AddNotification.cshtml
@model ColegioPublic.ViewsModel.NotificacionVM.AddEditNotificacionViewModel
@{
    ViewBag.Title = Model.NotificacionId.HasValue?"Modificar":"Agregar"+" Notificacion";
}
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">@(Model.NotificacionId.HasValue?"Modificar":"Agregar") Notificación</h4>
                <form class="form" action="@Url.Action("AddNotification","Notificacion")" method="post">
                    @Html.HiddenFor(x => x.NotificacionId)
                    @Html.HiddenFor(x => x.UsuarioSendId)

                    <div class="form-group row">
                        @Html.LabelFor(x => x.TipoNotificacionId, new { @class = "col-sm-2 col-form-label" })

                        <div class="col-sm-10">
                            @Html.DropDownListFor(x => x.TipoNotificacionId, new SelectList(Model.LstTipoNotificacion, "Value", "Text"), new { @class = "custom-select" })

                        </div>
                        @Html.ValidationMessageFor(x => x.TipoNotificacionId)
                    </div>
                    <div class="form-group mt-5 row">
                        @Html.LabelFor(x => x.Titulo, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group mt-5 row">
                        @Html.LabelFor(x => x.Comentario, new { @class = "col-2 col-form-label" })

                        <div class="col-10">
                            @Html.TextAreaFor(x => x.Comentario, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="card-body">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Guardar</button>
                            <a href="@Url.Action("Index","Notificacion")">Cancelar</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">

     
    </script>
}

ColegioPublic/Views/Notificacion/Index.cshtml
@model ColegioPublic.ViewsModel.UsuarioMovilVM.IndexUsuarioMovilViewModel
@{
    ViewBag.Title = "Notificaciones";
}

<h2>Lista de Usuarios Movil</h2>

@using (Ajax.BeginForm("_ListUsuarioMovil", "UsuarioMovil", new AjaxOptions
{//GetPatients is name of method in PatientController
    InsertionMode = InsertionMode.Replace, //target element(#patientList) will be replaced
    UpdateTargetId = "paged-section",
    LoadingElementId = "loader" // div with .gif loader - that is shown when data are loading
}))
{
    @Html.LabelFor(x => x.q, new { })
    <div class="input-group">

        @Html.TextBoxFor(x => x.q, new { @class = "form-control" })
        <button class="btn btn-success btn-sm" id="Filtrar"><i class="fa fa-search" aria-hidden="true"></i></button>
    </div>

}
<hr />
<div class="button-group text-right">
    <a href="@Url.Action("AddEditUsuarioMovil","UsuarioMovil")" class="btn btn-success"> <i class="fa fa-plus-circle" aria-hidden="true"></i> Nuevo Usuario</a>
</div>

<div class="table-responsive" id="paged-section">
    @{Html.RenderAction("_ListUsuarioMovil", Model);}
</div>

@section scripts{
    <script>

        $(function () {
                $("#paged-section").on("click",".eliminarNotificacion",function (e) {
      
                e.preventDefault();
                var url = $(this).attr("href");
                debugger;
                var formData = new FormData();
                Swal.fire({
                    title: 'Confirmación de Eliminación',
                    text: "Está seguro de Eliminar?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    cancelButtonText: 'Cancelar',
                    confirmButtonText: 'Si, Estoy seguro!'
                }).then((result) => {
                    if (result.value) {
                        /**/
                        $.ajax({
                            url: url,
                            type: "GET",
                            data: formData,
                            contentType: false,
                            processData: false,
                            async: false
                        }).done(function (data) {
                            var modelo = JSON.parse(JSON.stringify(data));
                            if (modelo.Value == true) {
                                Swal.fire(
                                    'Se Elimino Correctamente!',
                                    '',
                                    'success'
                                ).then((result) => {
                                    if (result) {
                                        $("#Filtrar").submit();
                                    }
                                });
                            } else {
                                Swal.fire(
                                    'Ocurrio algún error al Eliminar!',
                                    '',
                                    'error'
                                )
                            }
                        }).fail(function () {
                            Swal.fire(
                                'No se pudo Eliminar!',
                                'Aceptar!',
                                'error'
                            )

                        });
                        /**/
                    }
                })

            });
        });


    </script>
}

ColegioPublic/Views/Notificacion/_ListNotificacion.cshtml
@model ColegioPublic.ViewsModel.NotificacionVM._ListNotificacionViewModel
@{
    ViewBag.Title = "_ListNotificacion";
}

<h2>Lista de Notificaciones</h2>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Comentario</th>
            <th>Fecha</th>
            <th>Opciones</th>
        </tr>
    </thead>

    <tbody>
        @if (Model.LstRegistro.Count > 0)
        {
            foreach (var item in Model.LstRegistro)
            {
        <tr>
            <td>@item.Comentario</td>
            <td>@item.FechaRegistro.Value.ToShortDateString()</td>
            <td>
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Opciones</button>
                    <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(696px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                        <a class="dropdown-item" href="@Url.Action("AddEditNotificacion","Notificacion", new {NotificacionId = item.NotificacionId})">Editar</a>
                        <a class="dropdown-item eliminarNotificacion" href="@Url.Action("Delete","Notificacion", new {NotificacionId = item.NotificacionId})">Eliminar</a>
                    </div>
                </div>
            </td>
        </tr>
            }
        }

    </tbody>
</table>

ColegioPublic/Views/Notificacion/_ListUsuarioMovil.cshtml
@model ColegioPublic.ViewsModel.UsuarioMovilVM._ListUsuarioMovilViewModel
@using PagedList.Mvc;
@using PagedList;
@using ColegioPublic.Helper;

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Correo</th>
            <th>Telefono</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.LstRegistro.Count > 0)
        {
            foreach (var item in Model.LstRegistro)
            {
                <tr>
                    <td>@item.Nombre</td>
                    <td>@($"{item.ApellidosP} {item.ApellidosM}")</td>
                    <td>@item.Correo</td>
                    <td>@item.Telefono</td>
                    <td>
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Opciones</button>
                            <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(696px, 38px, 0px); top: 0px; left: 0px; will-change: transform;">
                                <a class="dropdown-item" href="@Url.Action("AddNotification","Notificacion", new {usuarioId = item.UsuarioId})">Agregar Notificación</a>
                                <a class="dropdown-item" href="@Url.Action("_ListNotificacion","Notificacion", new {usuarioId = item.UsuarioId})">Lista de Notificación</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
@Html.PagedListPager(Model.LstRegistro, p => Url.Action("_ListUsuarioMovil", new { p = p,model =Model.q }), PaginationHelper.AjaxPagerOptionsDefault)